const products = [
    { id: 1, name: 'Pizza Margarita', category: 'pizza', price: 640.00 },
    { id: 2, name: 'Pizza Especial', category: 'pizza', price: 720.00 },
    { id: 3, name: 'Slice Margarita', category: 'slice', price: 100.00 },
    { id: 4, name: 'Slice Especial', category: 'slice', price: 120.00 },
    { id: 5, name: 'Rissotto de Lomito', category: 'risotto', price: 320.00 },
    { id: 6, name: 'Rissotto de Funghi', category: 'risotto', price: 320.00 },
    { id: 7, name: 'Risotto de Carretiero', category: 'risotto', price: 320.00 },
    { id: 8, name: 'Rissotto de Pepperoni', category: 'risotto', price: 320.00},
    { id: 9, name: 'Refresco Lata', category: 'bebida', price: 80.00},
    { id: 10, name: 'Agua Mineral', category: 'bebida', price: 55.00 },
    { id: 11, name: 'Refresco Vaso Pequeño', category: 'bebida', price: 60.00 },
    { id: 12, name: 'Refresco Vaso Grande', category: 'bebida', price: 100.00 },
    { id: 13, name: 'Refresco Botella', category: 'bebida', price: 60.00 },
    { id: 14, name: 'Malta', category: 'bebida', price: 60.00 },
    { id: 15, name: 'Nestea Pequeño', category: 'bebida', price: 60.00 },
    { id: 16, name: 'Nestea Grande', category: 'bebida', price: 100.00 },
    { id: 17, name: 'Frozen Pequeño', category: 'bebida', price: 60.00 },
    { id: 18, name: 'Frozen Grande', category: 'bebida', price:  100.00 },
    { id: 19, name: 'Frozen Grande', category: 'bebida', price:  100.00 },
    { id: 20, name: 'Lipton Botella', category: 'bebida', price:  105.00 },
    { id: 21, name: 'Gatorade', category: 'bebida', price:  110.00 },
    { id: 22, name: 'Pasta Bologna', category: 'pasta', price:  320.00 },
    { id: 23, name: 'Pasta Napole', category: 'pasta', price:  320.00 },
    { id: 24, name: 'Pasta Boscaiola', category: 'pasta', price:  320.00 },
    { id: 25, name: 'Pasta Carbonara', category: 'pasta', price:  320.00 },
    { id: 26, name: 'Pasta Carretiero', category: 'pasta', price:  320.00 },
    { id: 27, name: 'Pasta Funghi', category: 'pasta', price:  320.00 },
    { id: 28, name: 'Pasta Alfredo', category: 'pasta', price:  320.00 },
    { id: 29, name: 'Pasta Amatriciana', category: 'pasta', price:  320.00 },    
  ];
  
  export default products;